# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160713_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
