# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imgportada'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imgportada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.imgportada'),
        ),
    ]
