# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_articulo_imgportada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imgportada',
        ),
        migrations.AlterField(
            model_name='imgportada',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
